// package graph

// // This file will be automatically regenerated based on the schema, any resolver implementations
// // will be copied through when generating and any unknown code will be moved to the end.
// // Code generated by github.com/99designs/gqlgen version v0.17.82

// import (
// 	"Gin_Event_App_Arc/graph/model"
// 	"context"
// 	"fmt"
// 	"strconv"
// )

// // CreateCategory is the resolver for the createCategory field.
// func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
// 	fmt.Println("Debugging hori yahan")
// 	category, err := r.CategoryRepo.Create(input.Name, *input.Description)
// 	if err != nil {
// 		return nil, err
// 	}
// 	fmt.Println("Category", category)
// 	return &model.Category{
// 		ID:          strconv.Itoa(category.ID),
// 		Name:        category.Name,
// 		Description: category.Description,
// 	}, nil
// }

// // CreateCourse is the resolver for the createCourse field.
// func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourse) (*model.Course, error) {
// 	course, err := r.CourseRepo.CreateCourse(input.Name, *input.Description)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return &model.Course{
// 		ID:          strconv.Itoa(course.ID),
// 		Name:        course.Name,
// 		Description: course.Description,
// 	}, nil
// }

// // Categories is the resolver for the categories field.
// func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
// 	allCategories, err := r.CategoryRepo.GetAll()
// 	if err != nil {
// 		return nil, err
// 	}
// 	var categoriesModelarr []*model.Category
// 	for _, category := range allCategories {
// 		categoriesModelarr = append(categoriesModelarr, &model.Category{
// 			ID:          strconv.Itoa(category.ID),
// 			Name:        category.Name,
// 			Description: category.Description,
// 		})
// 	}
// 	return categoriesModelarr, nil
// }

// // Courses is the resolver for the courses field.
// func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
// 	allCourses, err := r.CourseRepo.GetAllCourses()
// 	if err != nil {
// 		return nil, err
// 	}
// 	var courseModelarr []*model.Course
// 	for _, course := range allCourses {
// 		courseModelarr = append(courseModelarr, &model.Course{
// 			ID:          strconv.Itoa(course.ID),
// 			Name:        course.Name,
// 			Description: course.Description,
// 		})
// 	}
// 	return courseModelarr, nil
// }

// // Mutation returns MutationResolver implementation.
// func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// // Query returns QueryResolver implementation.
// func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// type mutationResolver struct{ *Resolver }
// type queryResolver struct{ *Resolver }

// // !!! WARNING !!!
// // The code below was going to be deleted when updating resolvers. It has been copied here so you have
// // one last chance to move it out of harms way if you want. There are two reasons this happens:
// //  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
// //    it when you're done.
// //  - You have helper methods in this file. Move them out to keep these resolver files clean.
// /*
// 	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
// 	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
// }
// func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
// 	panic(fmt.Errorf("not implemented: Todos - todos"))
// }
// */

package main
