package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"Gin_Event_App_Arc/graph/model"
	"Gin_Event_App_Arc/models"
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	category, err := r.CategoryRepo.Create(input.Name, *input.Description)
	if err != nil {
		return nil, err
	}
	return &model.Category{
		ID:          strconv.Itoa(category.ID),
		Name:        category.Name,
		Description: category.Description,
	}, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourse) (*model.Course, error) {
	course, err := r.CourseRepo.CreateCourse(input.Name, *input.Description)
	if err != nil {
		return nil, err
	}
	return &model.Course{
		ID:          strconv.Itoa(course.ID),
		Name:        course.Name,
		Description: course.Description,
	}, nil
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, file graphql.Upload) (*model.File, error) {
	data, err := io.ReadAll(file.File)
	if err != nil {
		return nil, err
	}
	// build DB model
	dbFile := &models.FileUpload{
		FileName:    file.Filename,
		ContentType: file.ContentType,
		Size:        len(data),
		Data:        data,
	}
	// call service (The code that I wrote Earlier)
	if err := r.FileUploadService.UploadFile(dbFile); err != nil {
		return nil, err
	}

	// build download URL (point to your existing REST route)
	// assume REST GET: /files/getById/:id on same host
	downloadURL := fmt.Sprintf("/files/getById/%d", dbFile.ID)

	// return GraphQL model
	return &model.File{
		ID:          strconv.Itoa(int(dbFile.ID)),
		Filename:    dbFile.FileName,
		ContentType: dbFile.ContentType,
		Size:        int32(dbFile.Size),
		DownloadURL: downloadURL,
	}, nil
}

// UpdateFile is the resolver for the updateFile field.
func (r *mutationResolver) UpdateFile(ctx context.Context, id string, file graphql.Upload) (*model.File, error) {
	dbID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	data, err := io.ReadAll(file.File)
	if err != nil {
		return nil, err
	}

	dbFile := &models.FileUpload{
		ID:          uint(dbID),
		FileName:    file.Filename,
		ContentType: file.ContentType,
		Size:        len(data),
		Data:        data,
	}
	updated, err := r.FileUploadService.UpdateFile(dbFile)
	if err != nil {
		return nil, err
	}

	return &model.File{
		ID:          strconv.Itoa(int(updated.ID)),
		Filename:    updated.FileName,
		ContentType: updated.ContentType,
		Size:        int32(updated.Size),
		DownloadURL: fmt.Sprintf("/files/getById/%d", updated.ID),
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, id string) (bool, error) {
	dbID, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}
	if err := r.FileUploadService.DeleteFile(dbID); err != nil {
		return false, err
	}
	return true, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	allCategories, err := r.CategoryRepo.GetAll()
	if err != nil {
		return nil, err
	}
	var categoriesModelarr []*model.Category
	for _, category := range allCategories {
		categoriesModelarr = append(categoriesModelarr, &model.Category{
			ID:          strconv.Itoa(category.ID),
			Name:        category.Name,
			Description: category.Description,
		})
	}
	return categoriesModelarr, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	allCourses, err := r.CourseRepo.GetAllCourses()
	if err != nil {
		return nil, err
	}
	var courseModelarr []*model.Course
	for _, course := range allCourses {
		courseModelarr = append(courseModelarr, &model.Course{
			ID:          strconv.Itoa(course.ID),
			Name:        course.Name,
			Description: course.Description,
		})
	}
	return courseModelarr, nil
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context) ([]*model.File, error) {
	all, err := r.FileUploadService.GetAllFiles()
	if err != nil {
		return nil, err
	}
	out := make([]*model.File, 0, len(all))
	for _, f := range all {
		out = append(out, &model.File{
			ID:          strconv.Itoa(int(f.ID)),
			Filename:    f.FileName,
			ContentType: f.ContentType,
			Size:        int32(f.Size),
			DownloadURL: fmt.Sprintf("/files/getById/%d", f.ID),
		})
	}
	return out, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id string) (*model.File, error) {
	dbID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	f, err := r.FileUploadService.GetFile(dbID)
	if err != nil {
		return nil, err
	}

	return &model.File{
		ID:          strconv.Itoa(int(f.ID)),
		Filename:    f.FileName,
		ContentType: f.ContentType,
		Size:        int32(f.Size),
		DownloadURL: fmt.Sprintf("/files/getById/%d", f.ID),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
